### ISSUE TITLE
Failed installation via paru/AUR

### ISSUE THREAD

**Issue by skyyy777** [neetly/figma-agent-linux#12]
> Compiling actix-codec v0.5.0
>    Compiling figma-agent-freetype-sys v0.2.0 (/home/witalij/.cache/paru/clone/figma-agent-linux/src/figma-agent-linux/crates/freetype-sys)
>    Compiling figma-agent-fontconfig-sys v0.2.0 (/home/witalij/.cache/paru/clone/figma-agent-linux/src/figma-agent-linux/crates/fontconfig-sys)
> error: failed to run custom build command for `figma-agent-freetype-sys v0.2.0 (/home/witalij/.cache/paru/clone/figma-agent-linux/src/figma-agent-linux/crates/freetype-sys)`
> 
> Caused by:
>   process didn't exit successfully: `/home/witalij/.cache/paru/clone/figma-agent-linux/src/figma-agent-linux/target/release/build/figma-agent-freetype-sys-541a2fcf6ca9bad9/build-script-build` (exit status: 101)
>   --- stdout
>   cargo:rerun-if-changed=./include/freetype.h
>   cargo:rerun-if-env-changed=FREETYPE2_NO_PKG_CONFIG
>   cargo:rerun-if-env-changed=PKG_CONFIG_x86_64-unknown-linux-gnu
>   cargo:rerun-if-env-changed=PKG_CONFIG_x86_64_unknown_linux_gnu
>   cargo:rerun-if-env-changed=HOST_PKG_CONFIG
>   cargo:rerun-if-env-changed=PKG_CONFIG
>   cargo:rerun-if-env-changed=FREETYPE2_STATIC
>   cargo:rerun-if-env-changed=FREETYPE2_DYNAMIC
>   cargo:rerun-if-env-changed=PKG_CONFIG_ALL_STATIC
>   cargo:rerun-if-env-changed=PKG_CONFIG_ALL_DYNAMIC
>   cargo:rerun-if-env-changed=PKG_CONFIG_PATH_x86_64-unknown-linux-gnu
>   cargo:rerun-if-env-changed=PKG_CONFIG_PATH_x86_64_unknown_linux_gnu
>   cargo:rerun-if-env-changed=HOST_PKG_CONFIG_PATH
>   cargo:rerun-if-env-changed=PKG_CONFIG_PATH
>   cargo:rerun-if-env-changed=PKG_CONFIG_LIBDIR_x86_64-unknown-linux-gnu
>   cargo:rerun-if-env-changed=PKG_CONFIG_LIBDIR_x86_64_unknown_linux_gnu
>   cargo:rerun-if-env-changed=HOST_PKG_CONFIG_LIBDIR
>   cargo:rerun-if-env-changed=PKG_CONFIG_LIBDIR
>   cargo:rerun-if-env-changed=PKG_CONFIG_SYSROOT_DIR_x86_64-unknown-linux-gnu
>   cargo:rerun-if-env-changed=PKG_CONFIG_SYSROOT_DIR_x86_64_unknown_linux_gnu
>   cargo:rerun-if-env-changed=HOST_PKG_CONFIG_SYSROOT_DIR
>   cargo:rerun-if-env-changed=PKG_CONFIG_SYSROOT_DIR
>   cargo:rerun-if-env-changed=PKG_CONFIG_SYSROOT_DIR
>   cargo:rerun-if-env-changed=SYSROOT
>   cargo:rerun-if-env-changed=FREETYPE2_STATIC
>   cargo:rerun-if-env-changed=FREETYPE2_DYNAMIC
>   cargo:rerun-if-env-changed=PKG_CONFIG_ALL_STATIC
>   cargo:rerun-if-env-changed=PKG_CONFIG_ALL_DYNAMIC
>   cargo:rustc-link-search=native=/usr/lib
>   cargo:rustc-link-lib=freetype
>   cargo:rerun-if-env-changed=PKG_CONFIG_x86_64-unknown-linux-gnu
>   cargo:rerun-if-env-changed=PKG_CONFIG_x86_64_unknown_linux_gnu
>   cargo:rerun-if-env-changed=HOST_PKG_CONFIG
>   cargo:rerun-if-env-changed=PKG_CONFIG
>   cargo:rerun-if-env-changed=FREETYPE2_STATIC
>   cargo:rerun-if-env-changed=FREETYPE2_DYNAMIC
>   cargo:rerun-if-env-changed=PKG_CONFIG_ALL_STATIC
>   cargo:rerun-if-env-changed=PKG_CONFIG_ALL_DYNAMIC
>   cargo:rerun-if-env-changed=PKG_CONFIG_PATH_x86_64-unknown-linux-gnu
>   cargo:rerun-if-env-changed=PKG_CONFIG_PATH_x86_64_unknown_linux_gnu
>   cargo:rerun-if-env-changed=HOST_PKG_CONFIG_PATH
>   cargo:rerun-if-env-changed=PKG_CONFIG_PATH
>   cargo:rerun-if-env-changed=PKG_CONFIG_LIBDIR_x86_64-unknown-linux-gnu
>   cargo:rerun-if-env-changed=PKG_CONFIG_LIBDIR_x86_64_unknown_linux_gnu
>   cargo:rerun-if-env-changed=HOST_PKG_CONFIG_LIBDIR
>   cargo:rerun-if-env-changed=PKG_CONFIG_LIBDIR
>   cargo:rerun-if-env-changed=PKG_CONFIG_SYSROOT_DIR_x86_64-unknown-linux-gnu
>   cargo:rerun-if-env-changed=PKG_CONFIG_SYSROOT_DIR_x86_64_unknown_linux_gnu
>   cargo:rerun-if-env-changed=HOST_PKG_CONFIG_SYSROOT_DIR
>   cargo:rerun-if-env-changed=PKG_CONFIG_SYSROOT_DIR
> 
>   --- stderr
>   thread 'main' panicked at 'Unable to find libclang: "couldn't find any valid shared libraries matching: ['libclang.so', 'libclang-*.so', 'libclang.so.*', 'libclang-*.so.*'], set the `LIBCLANG_PATH` environment variable to a path where one of these files can be found (invalid: [])"', /home/witalij/.cargo/registry/src/github.com-1ecc6299db9ec823/bindgen-0.60.1/src/lib.rs:2172:31
>   note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
> warning: build failed, waiting for other jobs to finish...
> error: failed to run custom build command for `figma-agent-fontconfig-sys v0.2.0 (/home/witalij/.cache/paru/clone/figma-agent-linux/src/figma-agent-linux/crates/fontconfig-sys)`
> 
> Caused by:
>   process didn't exit successfully: `/home/witalij/.cache/paru/clone/figma-agent-linux/src/figma-agent-linux/target/release/build/figma-agent-fontconfig-sys-9ddad7b59082012c/build-script-build` (exit status: 101)
>   --- stdout
>   cargo:rerun-if-changed=./include/fontconfig.h
>   cargo:rerun-if-env-changed=FONTCONFIG_NO_PKG_CONFIG
>   cargo:rerun-if-env-changed=PKG_CONFIG_x86_64-unknown-linux-gnu
>   cargo:rerun-if-env-changed=PKG_CONFIG_x86_64_unknown_linux_gnu
>   cargo:rerun-if-env-changed=HOST_PKG_CONFIG
>   cargo:rerun-if-env-changed=PKG_CONFIG
>   cargo:rerun-if-env-changed=FONTCONFIG_STATIC
>   cargo:rerun-if-env-changed=FONTCONFIG_DYNAMIC
>   cargo:rerun-if-env-changed=PKG_CONFIG_ALL_STATIC
>   cargo:rerun-if-env-changed=PKG_CONFIG_ALL_DYNAMIC
>   cargo:rerun-if-env-changed=PKG_CONFIG_PATH_x86_64-unknown-linux-gnu
>   cargo:rerun-if-env-changed=PKG_CONFIG_PATH_x86_64_unknown_linux_gnu
>   cargo:rerun-if-env-changed=HOST_PKG_CONFIG_PATH
>   cargo:rerun-if-env-changed=PKG_CONFIG_PATH
>   cargo:rerun-if-env-changed=PKG_CONFIG_LIBDIR_x86_64-unknown-linux-gnu
>   cargo:rerun-if-env-changed=PKG_CONFIG_LIBDIR_x86_64_unknown_linux_gnu
>   cargo:rerun-if-env-changed=HOST_PKG_CONFIG_LIBDIR
>   cargo:rerun-if-env-changed=PKG_CONFIG_LIBDIR
>   cargo:rerun-if-env-changed=PKG_CONFIG_SYSROOT_DIR_x86_64-unknown-linux-gnu
>   cargo:rerun-if-env-changed=PKG_CONFIG_SYSROOT_DIR_x86_64_unknown_linux_gnu
>   cargo:rerun-if-env-changed=HOST_PKG_CONFIG_SYSROOT_DIR
>   cargo:rerun-if-env-changed=PKG_CONFIG_SYSROOT_DIR
>   cargo:rerun-if-env-changed=PKG_CONFIG_SYSROOT_DIR
>   cargo:rerun-if-env-changed=SYSROOT
>   cargo:rerun-if-env-changed=FONTCONFIG_STATIC
>   cargo:rerun-if-env-changed=FONTCONFIG_DYNAMIC
>   cargo:rerun-if-env-changed=PKG_CONFIG_ALL_STATIC
>   cargo:rerun-if-env-changed=PKG_CONFIG_ALL_DYNAMIC
>   cargo:rustc-link-search=native=/usr/lib
>   cargo:rustc-link-lib=fontconfig
>   cargo:rustc-link-lib=freetype
>   cargo:rerun-if-env-changed=PKG_CONFIG_x86_64-unknown-linux-gnu
>   cargo:rerun-if-env-changed=PKG_CONFIG_x86_64_unknown_linux_gnu
>   cargo:rerun-if-env-changed=HOST_PKG_CONFIG
>   cargo:rerun-if-env-changed=PKG_CONFIG
>   cargo:rerun-if-env-changed=FONTCONFIG_STATIC
>   cargo:rerun-if-env-changed=FONTCONFIG_DYNAMIC
>   cargo:rerun-if-env-changed=PKG_CONFIG_ALL_STATIC
>   cargo:rerun-if-env-changed=PKG_CONFIG_ALL_DYNAMIC
>   cargo:rerun-if-env-changed=PKG_CONFIG_PATH_x86_64-unknown-linux-gnu
>   cargo:rerun-if-env-changed=PKG_CONFIG_PATH_x86_64_unknown_linux_gnu
>   cargo:rerun-if-env-changed=HOST_PKG_CONFIG_PATH
>   cargo:rerun-if-env-changed=PKG_CONFIG_PATH
>   cargo:rerun-if-env-changed=PKG_CONFIG_LIBDIR_x86_64-unknown-linux-gnu
>   cargo:rerun-if-env-changed=PKG_CONFIG_LIBDIR_x86_64_unknown_linux_gnu
>   cargo:rerun-if-env-changed=HOST_PKG_CONFIG_LIBDIR
>   cargo:rerun-if-env-changed=PKG_CONFIG_LIBDIR
>   cargo:rerun-if-env-changed=PKG_CONFIG_SYSROOT_DIR_x86_64-unknown-linux-gnu
>   cargo:rerun-if-env-changed=PKG_CONFIG_SYSROOT_DIR_x86_64_unknown_linux_gnu
>   cargo:rerun-if-env-changed=HOST_PKG_CONFIG_SYSROOT_DIR
>   cargo:rerun-if-env-changed=PKG_CONFIG_SYSROOT_DIR
> 
>   --- stderr
>   thread 'main' panicked at 'Unable to find libclang: "couldn't find any valid shared libraries matching: ['libclang.so', 'libclang-*.so', 'libclang.so.*', 'libclang-*.so.*'], set the `LIBCLANG_PATH` environment variable to a path where one of these files can be found (invalid: [])"', /home/witalij/.cargo/registry/src/github.com-1ecc6299db9ec823/bindgen-0.60.1/src/lib.rs:2172:31
>   note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
> ==> ERROR: A failure occurred in build().
>     Aborting...
> error: failed to build 'figma-agent-linux-0.2.0-1': 
> error: packages failed to build: figma-agent-linux-0.2.0-1
> 

Is this my fault? How can I fix this? I am switching from linux figma font helper if that helps :)

**Comment by latin-1** [comment]
I forgot adding `clang` to the `makedepends`. I've updated that AUR package, it should work now. Please let me know if there are any other problems. Thanks.

**Comment by skyyy777** [comment]
How can I uninstall the non AUR version to then install from AUR?

**Comment by latin-1** [comment]
```sh
systemctl --user disable --now figma-agent.service
rm -rf ~/.local/share/figma-agent-linux
rm -f ~/.local/share/systemd/user/figma-agent.service
systemctl --user daemon-reload
```

And then install from AUR regularly:

```sh
paru -S figma-agent-linux
systemctl --user enable --now figma-agent.service
```

**Comment by latin-1** [comment]
I'm going to close this issue as resolved. Feel free to open another issue if you have some problem else. Thanks again for your bug report!
