### ISSUE TITLE
Add a note for Brave browser.

### ISSUE THREAD

**Issue by latin-1** [neetly/figma-agent-linux#135]
https://github.com/neetly/figma-agent-linux/issues/64#issuecomment-1465218930
https://github.com/neetly/figma-agent-linux/issues/134#issuecomment-1868670410

**Comment by yurikoles** [comment]
I'm sorry that didn't try myself, but I wanted to mention that the very same issue may occur in any browser with [uBlock Origin's](https://ublockorigin.com/) [Block Outsider Intrusion into LAN](https://ublockorigin.github.io/uAssetsCDN/filters/lan-block.txt) filter enabled.
