### ISSUE TITLE
Add Ko-fi link

### ISSUE THREAD

**Issue by lutzseverino** [neetly/figma-agent-linux#168]
This completely underrated project has saved me a massive headache. I know there's a Patreon link, but I would rather donate some money through Ko-fi every time I stumble upon this repository instead of having a monthly payment.

I really want to send some money over as a sign of gratitude, so a Ko-fi link would be awesome. 

Thanks!

PS: The README would benefit from a notice to users to change their user-agents on their browsers.

**Comment by latin-1** [comment]
I'm having some difficulty setting up a Ko-fi account. Would you mind trying this instead? https://afdian.net/a/tokenize (currency is CNY)

PS: README updated ✨
