### ISSUE TITLE
Failed to connect to bus: No medium found

### ISSUE THREAD

**Issue by hikionori** [neetly/figma-agent-linux#35]
Hi
I use manjaro linux and install package via arch linux steps using pacaur. After installation i run systemctl and get this error message.
Failed to connect to bus: No medium found

What`s i should do?

**Comment by hikionori** [comment]
and I tried paru result same

**Comment by latin-1** [comment]
Do you use sudo to run that command? It should be run as a normal user. Please remove sudo and retry to see if it works. Thanks.

**Comment by hikionori** [comment]
yeah its work
thanks
sorry)
