### ISSUE TITLE
Support for glibc 2.31 (Debian 11 Bullseye)

### ISSUE THREAD

**Issue by juliennicouleaud** [neetly/figma-agent-linux#48]
Hi,
I was wondering if there was any way I could get this to work on Debian 11, which only has glibc 2.31 ?
Thanks a lot,
Julien

**Comment by juliennicouleaud** [comment]
This is the error I'm running into :

systemctl --user status figma-agent.service
● figma-agent.service - Figma Agent for Linux
     Loaded: loaded (/home/.../.local/share/systemd/user/figma-agent.service; enabled; vendor preset: enabled)
     Active: failed (Result: exit-code) since Tue 2022-12-13 22:16:33 CET; 24min ago
    Process: 69158 ExecStart=/home/.../.local/share/figma-agent/figma-agent (code=exited, status=1/FAILURE)
   Main PID: 69158 (code=exited, status=1/FAILURE)
        CPU: 2ms

~ : Starting Figma Agent for Linux...
~ : Started Figma Agent for Linux.
~ :  /home/.../.local/share/figma-agent/figma-agent: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.32' not found (required by /home/.../.local/share/figma-ag>
~ : /home/.../.local/share/figma-agent/figma-agent: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.33' not found (required by /home/.../.local/share/figma-ag>
~ : /home/.../.local/share/figma-agent/figma-agent: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by /home/.../.local/share/figma-ag>
~ : figma-agent.service: Main process exited, code=exited, status=1/FAILURE
~ : figma-agent.service: Failed with result 'exit-code'.

**Comment by latin-1** [comment]
Please try the latest version and see if it works for you. Thanks

**Comment by juliennicouleaud** [comment]
Thanks a lot, it works fine now!
