### ISSUE TITLE
[Help] The tool doesn't seem to be working

### ISSUE THREAD

**Issue by mani-rai** [neetly/figma-agent-linux#64]
I enabled and started the systemd service and is loaded and active. I also looked at fonts.conf and everything seems fine. I looked at gimp and it's importing MSFonts just fine. However, I can't get to work on figma-linux. Is there anyway to troubleshoot the problem?

OS: 5.15.94-1-MANJARO
Figma Agent: 0.2.6-1 (Installed from AUR)

**Comment by latin-1** [comment]
Hi,

Do you have the `figma-agent.socket` or `figma-agent.service` enabled?

```sh
systemctl --user is-enabled figma-agent.socket figma-agent.service
```

If neither is enabled, please run this command and visit figma.com to see if it works for you.

```sh
systemctl --user enable --now figma-agent.socket
```

You can also use the following command to check the status:

```sh
systemctl --user status figma-agent.socket figma-agent.service
```

Thanks.

**Comment by latin-1** [comment]
If the status shows no errors and it still doesn't work for you, please run this command and attach the results to this issue.

```sh
curl --header "Origin: https://www.figma.com" "http://localhost:18412/figma/font-files" > output
```

**Comment by latin-1** [comment]
> However, I can't get to work on figma-linux.

Wait, you mean you're using the [figma-linux](https://github.com/Figma-Linux/figma-linux) client, right? figma-linux takes a different approach to locating local fonts. This program (figma-agent-linux) is only compatible with the Web client (https://www.figma.com/).

**Comment by mani-rai** [comment]
Hey @latin-1, sorry for delayed response. I confirmed that figma agents are enabled. And [here](https://drive.google.com/file/d/1UPT6xEvkbEBy3AVAcNYnAdllbnyZlRct/view?usp=share_link) is the output of the curl command. I tried in both platform, can't get MSFonts in figma web.

**Comment by mani-rai** [comment]
[UPDATED]
It worked. It wasn't working in brave browser. That was so lame of me.

**Comment by latin-1** [comment]
The Brave browser appears to block websites from accessing localhost due to security/privacy concerns. I'm glad it's finally working out for you!
