### ISSUE TITLE
Job failed. See "journalctl -xe" for details.

### ISSUE THREAD

**Issue by trainspotter-rhld** [neetly/figma-agent-linux#98]
Error while installing it.

**Comment by latin-1** [comment]
Could you please attach the output of the following command?

```sh
journalctl --user -u figma-agent.service -u figma-agent.socket -xe
```

**Comment by dvnlx** [comment]
`❯ journalctl --user -u figma-agent.service -u figma-agent.socket -xe
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
Jul 04 14:46:47 novagon systemd[2550]: Listening on figma-agent.socket - Figma >
░░ Subject: A start job for unit UNIT has finished successfully
░░ Defined-By: systemd
░░ Support: https://lists.freedesktop.org/mailman/listinfo/systemd-devel
░░ 
░░ A start job for unit UNIT has finished successfully.
░░ 
░░ The job identifier is 18.
`

**Comment by dvnlx** [comment]
![image](https://github.com/neetly/figma-agent-linux/assets/88238063/48c022ae-c6ec-4d8c-a151-9ae76db030ad)
![image](https://github.com/neetly/figma-agent-linux/assets/88238063/e41b619d-b0bf-40c5-8186-76cdd2aee031)

**Comment by latin-1** [comment]
Not sure what happened. Could you please manually run the binary and see if it works?

```sh
~/.local/share/figma-agent/figma-agent
```

**Comment by Faraaz-Madni** [comment]
^Yep, you gotta uninstall figma-linux-font-helper to free up the port. 

You can also check what Process ID is using the listening port specified in your journalctl -xe by sudo fuser (listeningport)/tcp

**Comment by latin-1** [comment]
Closed due to inactivity. Feel free to open another issue if the problem still persists.
